name: nuevomockups
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  #sdk: ^3.7.2
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.1.10
  mongo_dart: ^0.10.0
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Calibri
      fonts:
      - asset: assets/fonts/calibri.ttf
      - asset: assets/fonts/calibrib.ttf
        weight: 700
      - asset: assets/fonts/calibrii.ttf
        style: italic
      - asset: assets/fonts/calibriz.ttf
        weight: 700
        style: italic
  uses-material-design: true

  assets:
    - assets/logoSena.png
    - assets/banner_superior.jpg
    - assets/fondo_textura.png
    - assets/fondo_textura_2.png
    - assets/Icono_Atomo.png
    - assets/Icono_Bombilla.png
    - assets/Icono_Proveta.png 
    - assets/Icono_Cohete.png
    - assets/Icono_Microscopio.png
    - assets/Icono_Molecula.png
    - assets/Icono_Planeta.png
    - assets/Icono_T_Ensayo.png
    - assets/Icono_video.png

#------------------- IMAGENES TITULO ------------------#

    - assets/titulo/titulo.png
    - assets/titulo/titulo_caracterisitcas.png
    - assets/titulo/Titulo_otras_caracteristicas.jpg
    - assets/titulo/Titulo_palabras_utiles.png
    - assets/titulo/Titulo_ejemplo.png

    - assets/titulo/Fondo_Supeior_Izquierda.png
    - assets/titulo/Fondo_Supeior_Derecha.png
    - assets/titulo/Fondo_Inferior_Derecha.png
    - assets/titulo/Fondo_Inferior_Izquierda.png

#---------- IMAGENES PlateamientonoProblemas ----------#

    - assets/PlanteamientoProblema/Planteamiento_del_Problema.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Definicion.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Metodologia.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_5W1H.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_5W1H.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_2_5W1H.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_3_5W1H.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Espina_De_Pescado.jpeg
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Como_Hacer_Una_Espina_De_Pescado.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_1_Espina_De_Pescado.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_2_Espina_De_Pescado.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Arbol_De_Problemas.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Esquema_de_Redaccion_Parte_1.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Esquema_de_Redaccion_Parte_2.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Como_Hacer_Arbol_De_Problemas.png
    - assets/PlanteamientoProblema/Planteamiento_del_Problema_Ejemplo_Arbol_De_Problemas.png


    - assets/PlanteamientoProblema/Fondo_Inferior_Derecha.png
    - assets/PlanteamientoProblema/Fondo_Supeior_Izquierda.png
    - assets/PlanteamientoProblema/Fondo_inferior_Izquierda.png
    - assets/PlanteamientoProblema/Fondo_superior_Derecha.png
    
#--------------- IMagenes Justificacion ----------------#

    - assets/Justificacion/Justificacion.png
    - assets/Justificacion/Justificacion_Pasos.png
    - assets/Justificacion/Justificacion_Consejos.png
    - assets/Justificacion/Justificacion_Ejemplo.png


    - assets/Justificacion/Fondo_Inferior_Derecha.png
    - assets/Justificacion/Fondo_Supeior_Izquierda.png
    - assets/Justificacion/Fondo_inferior_Izquierda.png
    - assets/Justificacion/Fondo_superior_Derecha.png

#--------------- IMAGENES OBJETIVOS ----------------#

    - assets/Objetivos/Objetivos.png
    - assets/Objetivos/Objetivos_Método_Smart_Texto.png
    - assets/Objetivos/Objetivos_Método_Smart_Titulo.png
    - assets/Objetivos/Objetivos_Método_Clear_Texto.png
    - assets/Objetivos/Objetivos_Método_Clear_Titulo.png
    - assets/Objetivos/Objetivos_Método_Dumb_texto.png
    - assets/Objetivos/Objetivos_Método_Dumb_Titulo.png
    - assets/Objetivos/Objetivos_Método_Grow.png
    - assets/Objetivos/Objetivos_Método_Pure.png
    - assets/Objetivos/Objetivos_Arbol_de_Objetivos.png

    - assets/Objetivos/Fondo_Inferior_Derecha.png
    - assets/Objetivos/Fondo_Supeior_Izquierda.png
    - assets/Objetivos/Fondo_inferior_Izquierda.png
    - assets/Objetivos/Fondo_superior_Derecha.png

#--------------- IMAGENES BIBLIOGRAFIA ----------------#

    - assets/bibliografia/Bibliografia.png
    - assets/bibliografia/Bibliografia_Ejemplo.png
    - assets/bibliografia/Bibliografia_Normas_APA.png
    - assets/bibliografia/Bibliografia_Ejemplo_APA.png
    - assets/bibliografia/Bibliografia_Normas_IEEE.png
    - assets/bibliografia/BiblioGrafia_Ejemplo_IEEE.png
    - assets/bibliografia/Bibliografia_Sitios_Web_Recomendados.png

    - assets/bibliografia/Fondo_Inferior_Derecha.png
    - assets/bibliografia/Fondo_Supeior_Izquierda.png
    - assets/bibliografia/Fondo_inferior_Izquierda.png
    - assets/bibliografia/Fondo_superior_Derecha.png

#--------------- IMAGENES METODOLOGIA ----------------# 

    - assets/Metodologia/Metodologia_Tipos_De_Metodologia.png
    - assets/Metodologia/Metodologia_Metodologia.png
    - assets/Metodologia/Metodologia_Tipos_De_Metodologia_Cualitativa.png
    - assets/Metodologia/Metodologia_Tipos_De_Metodologia_Cuantitativa.png  
    - assets/Metodologia/Metodologia_Tipos_De_Metodologia_Mixta.png
    - assets/Metodologia/Metodologia_Pasos_Crear.png
    - assets/Metodologia/Metodologia_Pasos_Crear2.png


    - assets/Metodologia/Fondo_Inferior_Derecha.png
    - assets/Metodologia/Fondo_Supeior_Izquierda.png
    - assets/Metodologia/Fondo_inferior_Izquierda.png
    - assets/Metodologia/Fondo_superior_Derecha.png

#--------------- IMAGENES CRONOGRAMA -----------------#

    - assets/Cronograma/Cronograma_como_crear_un_Cronograma.png
    - assets/Cronograma/Cronograma_Pasos.png
    - assets/Cronograma/Cronograma_Ejemplo.png

    - assets/Cronograma/Fondo_Inferior_Derecha.png
    - assets/Cronograma/Fondo_Supeior_Izquierda.png
    - assets/Cronograma/Fondo_inferior_Izquierda.png
    - assets/Cronograma/Fondo_superior_Derecha.png


#--------------- IMAGENES ACTIVIDADES ----------------#

    - assets/Actividades/Actividades.png
    - assets/Actividades/Actividades_Resultados.png
    - assets/Actividades/Actividades_Formulacion_De_Resultados.png


    - assets/Actividades/Fondo_Inferior_Derecha.png
    - assets/Actividades/Fondo_Supeior_Izquierda.png
    - assets/Actividades/Fondo_inferior_Izquierda.png
    - assets/Actividades/Fondo_superior_Derecha.png

#--------------- IMAGENES BUSQUEDA ----------------#

    - assets/Busqueda/Busqueda_Google_Academico.png
    - assets/Busqueda/Busqueda_Operadores_Booleanos.jpg
    - assets/Busqueda/Busqueda_Google_Alertas.png
    - assets/Busqueda/Busqueda_Google_Tendencias.png
    - assets/Busqueda/Busqueda_Objetivos.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Academico1.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Academico2.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Alertas1.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Alertas2.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Tendencias1.png
    - assets/Busqueda/Busqueda_Ejemplo_Google_Tendencias2.png

    - assets/Busqueda/Fondo_Inferior_Derecha.png
    - assets/Busqueda/Fondo_Supeior_Izquierda.png
    - assets/Busqueda/Fondo_inferior_Izquierda.png
    - assets/Busqueda/Fondo_superior_Derecha.png

#--------------- IMAGENES BASESDATOS ----------------#

    - assets/BasesDatos/Bases_De_Datos_Definicion.png
    - assets/BasesDatos/Bases_De_Datos_Que_Es.png
    - assets/BasesDatos/Bases_De_Datos_Biblioteca_Sena.jpg
    - assets/BasesDatos/Bases_De_Datos_Estado_Del_Arte.png
    - assets/BasesDatos/Bases_De_Datos_Estado_Del_Arte_Ejemplo.png
    - assets/BasesDatos/Bases_De_Datos_Antecedentes.png
    - assets/BasesDatos/Bases_De_Datos_Antecedentes_Ejemplo.png

    - assets/BasesDatos/Ejemplo1.png
    - assets/BasesDatos/Ejemplo2.png
    - assets/BasesDatos/Ejemplo3.png 

    - assets/BasesDatos/Fondo_inferior_Derecha.png
    - assets/BasesDatos/Fondo_superior_Izqiuerda.png



    - assets/Video/Fondo_inferior_Derecha.png
    - assets/Video/Fondo_superior_Izqiuerda.png

# --------------- IMAGENES Resumen -----------------#

    - assets/Resumen/1.png
    - assets/Resumen/2.png
    - assets/Resumen/3.png
    - assets/Resumen/4.png
    - assets/Resumen/5.png
    - assets/Resumen/6.png
    - assets/Resumen/7.png
    - assets/Resumen/8.png
    - assets/Resumen/9.png
    - assets/Resumen/10.png
    - assets/Resumen/11.png